{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | default (include "chart.fullname" .) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
