{{- if .Values.ingress.enabled }}
{{- $root := . -}}  {{/* Capture the global scope */}}
{{- $dynamicHost := (include "chart.ingressHost" $root) -}} {{/* Pass global scope to helper */}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name | default (include "chart.fullname" .) }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $dynamicHost | quote }} {{/* Use the pre-calculated variable */}}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ $   | quote }} {{/* Use the pre-calculated variable */}}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $root.Values.name }} {{/* Use $root to access values inside range */}}
                port:
                  number: {{ $root.Values.api_port }}
          {{- end }}
    {{- end }}
{{- end }}