{{- if .Values.secret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name | default (include "chart.fullname" .) }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  # Encrypted values should be provided (created with kubeseal) in values as `secret.encryptedData`
  encryptedData:
    {{- if .Values.secret.encryptedData }}
    {{- range $key, $value := .Values.secret.encryptedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.name | default (include "chart.fullname" .) }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
{{- end }}
