{{- if .Values.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "chart.fullname" .) .Values.tlsSecret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecret.tls.crt | quote }}
  tls.key: {{ .Values.tlsSecret.tls.key | quote }}
{{- end }}
