apiVersion: v2
name: my-app
description: My Application Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - deployment
  - service
maintainers:
  - name: Ahmed Faqehi
    email: ahmadpsn7@gmail.com
